Keycloak.Net.sln
global.json
src/Keycloak.Net/Users/KeycloakClient.cs
test/Keycloak.Net.Tests/EmbraceTests/KeycloakClientShould.cs
test/Keycloak.Net.Tests/appsettings.TEMPLATE

Improve user creation by returning an id that was created.

Improve user creation

---

src/Keycloak.Net/Models/Clients/Client.cs

Extend Client class with a single property Secret in order to allow Client's secret to be set.

Extend Keycloak client with Secret property.

---

src/Keycloak.Net/KeycloakClient.cs
src/Keycloak.Net/Models/Groups/Group.cs

Added are more groups fields (realm and client roles, attributes, sugroups)

Improve support for groups

---

src/Keycloak.Net/Models/Users/SetPasswordResponse.cs
src/Keycloak.Net/Users/KeycloakClient.cs

Return error in case password policy isn't met

Set password method error handling support

---

src/Keycloak.Net/Models/Groups/Group.cs

Type change from IDictionary<string,string> to IDictionary<string,IEnumerable<string>>.

Fix attributes type for group

---

src/Keycloak.Net/Groups/KeycloakClient.cs

Added support for retrieving group users using paging.

Group users pagination

---

src/Keycloak.Net/Models/Roles/Role.cs

Add Description and Attributes to Role model

Role model: add Description and Attributes

---

src/Keycloak.Net/Models/Clients/Client.cs

AuthorizationServicesEnabled is a flag to distinguish Resource Servers among Clients.

Client is extended with a new property AuthorizationServicesEnabled

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
src/Keycloak.Net/Common/Converters/AuthorizationPermissionTypeConverter.cs
src/Keycloak.Net/Common/Converters/DecisionStrategiesConverter.cs
src/Keycloak.Net/Common/Converters/PolicyDecisionLogicConverter.cs
src/Keycloak.Net/Models/Clients/AuthorizationPermission.cs
test/Keycloak.Net.Tests/ClientAuthorization/KeycloakClientShould.cs

Introduce new KC entity named 'AuthorizationPermission'
CRUD methods and basic tests

Support for client authorization permissions

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
src/Keycloak.Net/Common/Converters/PolicyTypeConverter.cs
src/Keycloak.Net/Models/Clients/AuthorizationPermission.cs
src/Keycloak.Net/Models/Clients/RolePolicy.cs

Introduction of the new entity RolePolicy and CRUD methods.

add support for role policy

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
src/Keycloak.Net/Common/Converters/PolicyTypeConverter.cs
src/Keycloak.Net/Models/Clients/RolePolicy.cs

support for retrieval of permission associated entities:
- associatedPolicies
- scopes
- resources

permission associated data retrieval 

---

src/Keycloak.Net/AuthorizationScope/KeycloakClient.cs
src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
src/Keycloak.Net/Models/AuthorizationScopes/AuthorizationScope.cs
src/Keycloak.Net/Models/Resources/Resource.cs
src/Keycloak.Net/Resource/KeycloakClient.cs

Implementation of authorization scopes

Authorization scopes

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs

fix request paths for associated resources retrieval

fix request paths for associated resources retrieval

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs

Deserialize response in policy creation result

Deserialize response in policy creation result

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs

add filtering query params to policy retrieval method

improve authorization policy retrieval

---

src/Keycloak.Net/Common/Converters/PolicyTypeConverter.cs
src/Keycloak.Net/Models/Clients/RolePolicy.cs

Adds missing policy type [PolicyType.Js] and updates converter related to prevent issue with PolicyType serialization.

policy type conversion hotfix

---

src/Keycloak.Net/Clients/KeycloakClient.cs
test/Keycloak.Net.Tests/EmbraceTests/KeycloakClientShould.cs

Re-implement original CreateClientAsync using common code

Re-implement original CreateClientAsync using common code

---

src/Keycloak.Net/Models/Roles/Role.cs

Role attributes

---

src/Keycloak.Net/ClientAuthorization/KeycloakClient.cs
src/Keycloak.Net/Models/Clients/Policy.cs

Add user policy and CRUD methods

Add support for user policies

---

src/Keycloak.Net/Models/Clients/Policy.cs

add missing policy config
